version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=grpc_gql
      - TZ=Asia/Tokyo